# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_postdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date posted'),
        ),
    ]
