# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160818_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_auther',
            new_name='blog_author',
        ),
    ]
