# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160818_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(blank=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date commented.')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
                ('comment_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
        ),
    ]
