# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['blog_postdate']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_date']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_postdate',
            field=models.DateTimeField(verbose_name='Date posted'),
        ),
        migrations.AddField(
            model_name='like',
            name='blog_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
    ]
