# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160820_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_private',
            field=models.BooleanField(default=False),
        ),
    ]
